# Generated by Django 2.2.9 on 2020-08-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(default='Perfil', max_length=100),
        ),
    ]
