# Generated by Django 2.2.9 on 2020-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
