# Generated by Django 2.2.7 on 2020-01-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0002_auto_20200119_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name_plural': 'personagens'},
        ),
    ]
