# Generated by Django 2.2.7 on 2020-01-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0003_auto_20200119_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='historia',
        ),
        migrations.AddField(
            model_name='personagem',
            name='nivel_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vh_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vh_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vh_des',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vh_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vh_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vh_sab',
            field=models.IntegerField(default=0),
        ),
    ]
