# Generated by Django 2.2.7 on 2020-01-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0006_auto_20200119_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='base_for',
            new_name='baseFor',
        ),
    ]
