# Generated by Django 2.2.7 on 2020-01-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0007_auto_20200119_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='baseFor',
            new_name='base_for',
        ),
    ]
