# Generated by Django 2.2.7 on 2020-01-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0010_raca_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseDePersonagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.Classe')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.Personagem')),
            ],
        ),
        migrations.AddField(
            model_name='personagem',
            name='classes',
            field=models.ManyToManyField(through='personagem.ClasseDePersonagem', to='personagem.Classe'),
        ),
    ]
