# Generated by Django 2.2.7 on 2020-01-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
        ('personagem', '0011_auto_20200119_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='campanha',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Campanha'),
        ),
        migrations.AlterField(
            model_name='traco',
            name='tipo',
            field=models.CharField(choices=[('R', 'Raca'), ('C', 'Classe')], default='Raca', max_length=1),
        ),
    ]
