# Generated by Django 2.2.7 on 2020-01-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0012_auto_20200119_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traco',
            name='tipo',
        ),
    ]
