# Generated by Django 2.2.9 on 2020-02-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0014_auto_20200119_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('PER', 'Persuação'), ('FUR', 'Furtividade'), ('INV', 'Investigação'), ('ADE', 'Adestrar animais'), ('ENG', 'Enganação'), ('ACR', 'Acrobacia'), ('NAT', 'Natureza'), ('ITM', 'Intimidação'), ('HIS', 'História'), ('PRE', 'Prestidigitação'), ('PER', 'Percepção'), ('REL', 'Religião'), ('INT', 'Intuição'), ('SOB', 'Sobrevivência'), ('ATU', 'Atuação'), ('MED', 'Medicina'), ('ATL', 'Atletismo'), ('ARC', 'Arcanismo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArmaS', 'Armas Simples'), ('ArdrL', 'Armaduras Leves'), ('ArmaM', 'Armas Marcials'), ('ArdrM', 'Armaduras Médias'), ('ArdrP', 'Armaduras Pesadas')], max_length=5),
        ),
    ]
