# Generated by Django 2.2.9 on 2020-02-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0015_auto_20200208_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('NAT', 'Natureza'), ('ADE', 'Adestrar animais'), ('ATL', 'Atletismo'), ('MED', 'Medicina'), ('SOB', 'Sobrevivência'), ('ATU', 'Atuação'), ('ARC', 'Arcanismo'), ('PRE', 'Prestidigitação'), ('ACR', 'Acrobacia'), ('PER', 'Persuação'), ('INV', 'Investigação'), ('INT', 'Intuição'), ('ENG', 'Enganação'), ('ITM', 'Intimidação'), ('REL', 'Religião'), ('HIS', 'História'), ('FUR', 'Furtividade'), ('PER', 'Percepção')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArmaM', 'Armas Marcials'), ('ArdrL', 'Armaduras Leves'), ('ArmaS', 'Armas Simples'), ('ArdrP', 'Armaduras Pesadas'), ('ArdrM', 'Armaduras Médias')], max_length=5),
        ),
    ]
