# Generated by Django 2.2.9 on 2020-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0016_auto_20200208_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('SOB', 'Sobrevivência'), ('INV', 'Investigação'), ('ATU', 'Atuação'), ('ADE', 'Adestrar animais'), ('NAT', 'Natureza'), ('INT', 'Intuição'), ('MED', 'Medicina'), ('PRE', 'Prestidigitação'), ('ACR', 'Acrobacia'), ('ARC', 'Arcanismo'), ('HIS', 'História'), ('REL', 'Religião'), ('ENG', 'Enganação'), ('ITM', 'Intimidação'), ('PER', 'Persuação'), ('FUR', 'Furtividade'), ('PER', 'Percepção'), ('ATL', 'Atletismo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArdrM', 'Armaduras Médias'), ('ArdrP', 'Armaduras Pesadas'), ('ArdrL', 'Armaduras Leves'), ('ArmaM', 'Armas Marcials'), ('ArmaS', 'Armas Simples')], max_length=5),
        ),
    ]
