# Generated by Django 2.2.9 on 2020-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0017_auto_20200223_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('INT', 'Intuição'), ('ACR', 'Acrobacia'), ('HIS', 'História'), ('ARC', 'Arcanismo'), ('FUR', 'Furtividade'), ('INV', 'Investigação'), ('REL', 'Religião'), ('ADE', 'Adestrar animais'), ('MED', 'Medicina'), ('ITM', 'Intimidação'), ('PRE', 'Prestidigitação'), ('SOB', 'Sobrevivência'), ('ENG', 'Enganação'), ('NAT', 'Natureza'), ('PER', 'Persuação'), ('PER', 'Percepção'), ('ATL', 'Atletismo'), ('ATU', 'Atuação')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArdrL', 'Armaduras Leves'), ('ArmaS', 'Armas Simples'), ('ArdrP', 'Armaduras Pesadas'), ('ArdrM', 'Armaduras Médias'), ('ArmaM', 'Armas Marcials')], max_length=5),
        ),
    ]
