# Generated by Django 2.2.9 on 2020-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0018_auto_20200301_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagem',
            options={},
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='classes',
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('HIS', 'História'), ('PER', 'Percepção'), ('SOB', 'Sobrevivência'), ('PER', 'Persuação'), ('NAT', 'Natureza'), ('MED', 'Medicina'), ('ADE', 'Adestrar animais'), ('ATU', 'Atuação'), ('ENG', 'Enganação'), ('ITM', 'Intimidação'), ('FUR', 'Furtividade'), ('REL', 'Religião'), ('PRE', 'Prestidigitação'), ('INV', 'Investigação'), ('ATL', 'Atletismo'), ('INT', 'Intuição'), ('ACR', 'Acrobacia'), ('ARC', 'Arcanismo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArdrL', 'Armaduras Leves'), ('ArdrM', 'Armaduras Médias'), ('ArmaM', 'Armas Marcials'), ('ArmaS', 'Armas Simples'), ('ArdrP', 'Armaduras Pesadas')], max_length=5),
        ),
        migrations.DeleteModel(
            name='ClasseDePersonagem',
        ),
    ]
