# Generated by Django 2.2.9 on 2020-08-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_classe_idioma_pericia_proficiencia_raca_traco'),
        ('personagem', '0019_auto_20200802_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonagemClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.Classe')),
            ],
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='campanha',
        ),
        migrations.RemoveField(
            model_name='raca',
            name='campanha',
        ),
        migrations.RemoveField(
            model_name='raca',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='raca',
            name='tracos',
        ),
        migrations.RemoveField(
            model_name='traco',
            name='campanha',
        ),
        migrations.AlterField(
            model_name='personagem',
            name='raca',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Raca'),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Pericia',
        ),
        migrations.DeleteModel(
            name='Proficiencia',
        ),
        migrations.DeleteModel(
            name='Raca',
        ),
        migrations.DeleteModel(
            name='Traco',
        ),
        migrations.AddField(
            model_name='personagem',
            name='classes',
            field=models.ManyToManyField(through='personagem.PersonagemClasse', to='campanha.Classe'),
        ),
    ]
