# Generated by Django 2.2.9 on 2020-09-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0020_auto_20200803_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagemclasse',
            name='personagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personagem.Personagem'),
            preserve_default=False,
        ),
    ]
