# Generated by Django 2.2.7 on 2020-01-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0004_auto_20200119_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='vh_car',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vh_con',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vh_des',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vh_for',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vh_int',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vh_sab',
            field=models.IntegerField(default=10),
        ),
    ]
