# Generated by Django 2.2.7 on 2020-01-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
        ('personagem', '0008_auto_20200119_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campanha', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Traco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('C', 'Classe'), ('R', 'Raca')], default='Raca', max_length=1)),
                ('campanha', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_customizado', models.BooleanField(default=False)),
                ('vh_for', models.IntegerField(default=0)),
                ('vh_des', models.IntegerField(default=0)),
                ('vh_con', models.IntegerField(default=0)),
                ('vh_int', models.IntegerField(default=0)),
                ('vh_sab', models.IntegerField(default=0)),
                ('vh_car', models.IntegerField(default=0)),
                ('campanha', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Campanha')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personagem.Idioma')),
                ('tracos', models.ManyToManyField(to='personagem.Traco')),
            ],
        ),
        migrations.AddField(
            model_name='personagem',
            name='raca',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personagem.Raca'),
        ),
    ]
