# Generated by Django 2.2.7 on 2020-01-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0009_auto_20200119_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
