# Generated by Django 2.2.9 on 2020-08-23 19:30

from django.db import migrations, models
import django.db.models.deletion
import sessao.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_perfil_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[sessao.models.validate_message_content])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='usuario.Perfil')),
            ],
        ),
    ]
