# Generated by Django 2.2.9 on 2020-08-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0003_auto_20200809_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventura',
            name='campanha',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Campanha'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='campanha',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha.Aventura'),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('PRE', 'Prestidigitação'), ('NAT', 'Natureza'), ('ATL', 'Atletismo'), ('ADE', 'Adestrar animais'), ('FUR', 'Furtividade'), ('PER', 'Percepção'), ('HIS', 'História'), ('SOB', 'Sobrevivência'), ('ACR', 'Acrobacia'), ('ARC', 'Arcanismo'), ('REL', 'Religião'), ('INV', 'Investigação'), ('ITM', 'Intimidação'), ('PER', 'Persuação'), ('ATU', 'Atuação'), ('MED', 'Medicina'), ('ENG', 'Enganação'), ('INT', 'Intuição')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArdrP', 'Armaduras Pesadas'), ('ArmaM', 'Armas Marcials'), ('ArdrL', 'Armaduras Leves'), ('ArmaS', 'Armas Simples'), ('ArdrM', 'Armaduras Médias')], max_length=5),
        ),
    ]
