# Generated by Django 2.2.9 on 2020-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0004_auto_20200809_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessao',
            old_name='campanha',
            new_name='aventura',
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('ARC', 'Arcanismo'), ('ACR', 'Acrobacia'), ('REL', 'Religião'), ('PRE', 'Prestidigitação'), ('ADE', 'Adestrar animais'), ('HIS', 'História'), ('SOB', 'Sobrevivência'), ('ATL', 'Atletismo'), ('NAT', 'Natureza'), ('MED', 'Medicina'), ('PER', 'Persuação'), ('FUR', 'Furtividade'), ('ATU', 'Atuação'), ('ENG', 'Enganação'), ('PER', 'Percepção'), ('INT', 'Intuição'), ('ITM', 'Intimidação'), ('INV', 'Investigação')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArdrM', 'Armaduras Médias'), ('ArmaS', 'Armas Simples'), ('ArmaM', 'Armas Marcials'), ('ArdrP', 'Armaduras Pesadas'), ('ArdrL', 'Armaduras Leves')], max_length=5),
        ),
    ]
