# Generated by Django 2.2.9 on 2020-08-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0005_auto_20200809_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('REL', 'Religião'), ('ARC', 'Arcanismo'), ('FUR', 'Furtividade'), ('NAT', 'Natureza'), ('ACR', 'Acrobacia'), ('ADE', 'Adestrar animais'), ('MED', 'Medicina'), ('SOB', 'Sobrevivência'), ('ENG', 'Enganação'), ('ITM', 'Intimidação'), ('ATL', 'Atletismo'), ('INV', 'Investigação'), ('HIS', 'História'), ('INT', 'Intuição'), ('PER', 'Percepção'), ('PER', 'Persuação'), ('PRE', 'Prestidigitação'), ('ATU', 'Atuação')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArdrL', 'Armaduras Leves'), ('ArdrM', 'Armaduras Médias'), ('ArmaM', 'Armas Marcials'), ('ArdrP', 'Armaduras Pesadas'), ('ArmaS', 'Armas Simples')], max_length=5),
        ),
        migrations.CreateModel(
            name='CaracteristicasClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.Classe')),
            ],
        ),
    ]
