# Generated by Django 2.2.9 on 2020-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0006_auto_20200809_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('INV', 'Investigação'), ('ADE', 'Adestrar animais'), ('ARC', 'Arcanismo'), ('HIS', 'História'), ('ACR', 'Acrobacia'), ('REL', 'Religião'), ('PER', 'Percepção'), ('SOB', 'Sobrevivência'), ('INT', 'Intuição'), ('MED', 'Medicina'), ('ATU', 'Atuação'), ('ITM', 'Intimidação'), ('PER', 'Persuação'), ('ATL', 'Atletismo'), ('FUR', 'Furtividade'), ('NAT', 'Natureza'), ('ENG', 'Enganação'), ('PRE', 'Prestidigitação')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArmaS', 'Armas Simples'), ('ArdrP', 'Armaduras Pesadas'), ('ArdrM', 'Armaduras Médias'), ('ArmaM', 'Armas Marcials'), ('ArdrL', 'Armaduras Leves')], max_length=5),
        ),
    ]
