# Generated by Django 2.2.9 on 2020-08-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0007_auto_20200823_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raca',
            name='tracos',
        ),
        migrations.AddField(
            model_name='raca',
            name='campanha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campanha.Campanha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traco',
            name='raca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campanha.Raca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('ITM', 'Intimidação'), ('ACR', 'Acrobacia'), ('FUR', 'Furtividade'), ('NAT', 'Natureza'), ('PRE', 'Prestidigitação'), ('ATL', 'Atletismo'), ('HIS', 'História'), ('ATU', 'Atuação'), ('INV', 'Investigação'), ('PER', 'Percepção'), ('MED', 'Medicina'), ('PER', 'Persuação'), ('ENG', 'Enganação'), ('REL', 'Religião'), ('SOB', 'Sobrevivência'), ('ARC', 'Arcanismo'), ('INT', 'Intuição'), ('ADE', 'Adestrar animais')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='nome',
            field=models.CharField(choices=[('ArmaS', 'Armas Simples'), ('ArmaM', 'Armas Marcials'), ('ArdrL', 'Armaduras Leves'), ('ArdrM', 'Armaduras Médias'), ('ArdrP', 'Armaduras Pesadas')], max_length=5),
        ),
        migrations.AlterField(
            model_name='raca',
            name='idioma',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='traco',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.Campanha'),
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
    ]
