# Generated by Django 2.2.9 on 2020-08-23 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0008_auto_20200823_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='pericias',
        ),
        migrations.AddField(
            model_name='classe',
            name='pericias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('PER', 'Percepção'), ('PER', 'Persuação'), ('FUR', 'Furtividade'), ('INT', 'Intuição'), ('ATL', 'Atletismo'), ('ARC', 'Arcanismo'), ('SOB', 'Sobrevivência'), ('INV', 'Investigação'), ('PRE', 'Prestidigitação'), ('ACR', 'Acrobacia'), ('HIS', 'História'), ('MED', 'Medicina'), ('ITM', 'Intimidação'), ('ENG', 'Enganação'), ('NAT', 'Natureza'), ('0', 'VAZIO'), ('REL', 'Religião'), ('ATU', 'Atuação'), ('ADE', 'Adestrar animais')], default='0', max_length=3), default=['0'], size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='classe',
            name='proficiencias',
        ),
        migrations.AddField(
            model_name='classe',
            name='proficiencias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('ArdrM', 'Armaduras Médias'), ('ArdrL', 'Armaduras Leves'), ('ArmaS', 'Armas Simples'), ('0', 'VAZIO'), ('ArdrP', 'Armaduras Pesadas'), ('ArmaM', 'Armas Marcials')], default='0', max_length=5), default=['0'], size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pericia',
        ),
        migrations.DeleteModel(
            name='Proficiencia',
        ),
    ]
