# Generated by Django 2.2.9 on 2020-08-23 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0009_auto_20200823_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='pericias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('PRE', 'Prestidigitação'), ('PER', 'Percepção'), ('FUR', 'Furtividade'), ('NAT', 'Natureza'), ('ITM', 'Intimidação'), ('ADE', 'Adestrar animais'), ('PER', 'Persuação'), ('ARC', 'Arcanismo'), ('ATL', 'Atletismo'), ('0', 'VAZIO'), ('SOB', 'Sobrevivência'), ('ATU', 'Atuação'), ('ACR', 'Acrobacia'), ('MED', 'Medicina'), ('ENG', 'Enganação'), ('INT', 'Intuição'), ('HIS', 'História'), ('REL', 'Religião'), ('INV', 'Investigação')], default='0', max_length=3), size=None),
        ),
        migrations.AlterField(
            model_name='classe',
            name='proficiencias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('ArdrL', 'Armaduras Leves'), ('ArmaS', 'Armas Simples'), ('0', 'VAZIO'), ('ArmaM', 'Armas Marcials'), ('ArdrP', 'Armaduras Pesadas'), ('ArdrM', 'Armaduras Médias')], default='0', max_length=5), size=None),
        ),
    ]
